# Generated by Django 4.2.7 on 2023-11-22 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idroles', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
                ('fecha_de_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('idlogin', models.AutoField(db_column='idlogin', primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=128)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fk_roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiOracle.roles')),
            ],
        ),
    ]
